config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'welcome#index'
  
  resources :artists
  resources :albums do
    resources :comments, module: :albums
  end
  resources :songs do
    resources :comments, module: :songs
  end
  
  get 'get_albums_of_artist/:artist_id' => 'songs#get_albums_of_artist'
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  has_many :albums, dependent: :destroy

  validates :name, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 15 }
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @artists = Artist.all
  end
  
  def new
    @artist = Artist.new
  end
  
  def create
    @artist = Artist.new(artist_params)
 
    if @artist.save
      redirect_to @artist
    else
      render 'new'
    end

  end
  
  def show
    @artist = Artist.find(params[:id])
  end
  
  def edit
    @artist = Artist.find(params[:id])
  end
  
  def update
    @artist = Artist.find(params[:id])
   
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render 'edit'
    end
  end
  
  private
    def artist_params
      params.require(:artist).permit(:name, :description)
    end
  
  
    
end

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>
 
<%= form_for :artist, url: artist_path(@artist), method: :patch do |f| %>
  
  <%= render :partial => "layouts/error", :locals => {:object => @artist} %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Artists</h1>
 <%= link_to 'New artist', new_artist_path, class: "btn btn-primary" %>
 <br><br>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>View</th>
     <th>Edit</th>
  </tr>
 
  <% @artists.each do |artist| %>
    <tr>
      <td><%= artist.name %></td>
      <td><%= artist.description %></td>
      <td><%= link_to 'Show', artist_path(artist) %></td>
      <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    </tr>
  <% end %>
</table>

app/views/artists/new.html.erb
<h1>Create an artist:</h1>
<%= form_for :artist, url: artists_path do |f| %>

  <%= render :partial => "layouts/error", :locals => {:object => @artist} %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<h1>View Artist</h1>
<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @artist.description %>
</p>


<%= link_to 'Back', artists_path %>