config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'welcome#index'
  
  resources :artists
  resources :albums do
    resources :comments, module: :albums
  end
  resources :songs do
    resources :comments, module: :songs
  end
  
  get 'get_albums_of_artist/:artist_id' => 'songs#get_albums_of_artist'
  

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
  belongs_to :artist
  has_many :comments, as: :commentable

  validates :title, presence: true, length: { minimum: 5 }
  validates :lyrics, presence: true
  validates :album_id, presence: true
  validates :artist_id, presence: true

  ratyrate_rateable "quality"

end

app/controllers/songs/comments_controller.rb
class Songs::CommentsController < CommentsController
    before_action :set_commentable
    
    private
        def set_commentable
            @commentable = Song.find(params[:song_id])
        end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :authenticate_user!

  def index
    # if params['sort_by'] == "title"
    #   @songs = Song.order(:title).paginate(:page => params[:page], :per_page => 2)
    # else
    #   @songs = Song.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 2)
    # end

    @songs ||= find_songs
    puts "======================================================"
  end

  def new
    @song = current_user.songs.new
    @artists = Artist.all
    @albums = nil
  end

  def create
    @song = current_user.songs.new(song_params)

    @artists = Artist.all
    @albums = Album.where(artist_id: params[:song][:artist_id]) if params[:song][:artist_id] != nil

    if @song.save
      redirect_to @song
    else
      render 'new'
    end

  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])

    @artists = Artist.all
    @albums = Album.where(artist_id: @song.artist_id) if @song.artist_id != nil

    if @song.user != current_user
      redirect_to @song
    end
  end

  def update
    @song = Song.find(params[:id])

    @artists = Artist.all
    @albums = Album.where(artist_id: params[:song][:artist_id]) if params[:song][:artist_id] != nil

    if @song.user != current_user
      redirect_to @song
    end

    if @song.update(song_params)
      redirect_to @song
    else
      render 'edit'
    end
  end

  def get_albums_of_artist
    @artist = Artist.find(params[:artist_id])
    @albums = @artist.albums

    result_str = '<option value="">Please select your album</option>'

    @albums.each do |album|
      result_str = result_str + "<option value='#{album.id}'>#{album.name}</option>"
    end


    render :json => {"result": result_str}
  end

  private

  def song_params
    params.require(:song).permit(:title, :lyrics, :youtube_url, :album_id, :artist_id)
  end

  def find_songs
    songs = Song.includes(:album, :artist).paginate(:page => params[:page], :per_page => 2)
    songs = songs.order(updated_at: :desc) if !params[:sort_by].present?
    songs = songs.order(:title) if (params[:sort_by].present? and params[:sort_by] == 'title')
    songs
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/edit.html.erb
<h1>Editing song</h1>
 
<%= form_for :song, url: song_path(@song), method: :patch do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
    <%  if @song.errors[:title].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:title].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>
 
  <p>
    <%= f.label :lyrics %><br>
    <%= f.text_area :lyrics, class: "form-control lyrics" %>
    <%  if @song.errors[:lyrics].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:lyrics].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>

  <p>
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url, class: "form-control" %>
  </p>

  <p>
    <div><b>Select the artist:</b></div>
    <%= f.collection_select :artist_id, @artists, :id, :name, prompt: true %>
    <%  if @song.errors[:artist_id].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:artist_id].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>
  
  <p>
    <div><b>Select the album:</b></div>
      <% if @albums != nil %>
        <%= f.collection_select :album_id, @albums , :id, :name, prompt: true  %>
      <% else %>
        <select name="song[album_id]" id="song_album_id">
          <option value="">Please select</option>
        <select>
      <% end %>
    <%  if @song.errors[:album_id].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:album_id].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', songs_path %>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#song_artist_id").on('change',function(){
      var artist_id = $(this).val();
      if (artist_id){
         $.ajax({url: "/get_albums_of_artist/" + artist_id, dataType: "json", success: function(result){
          $("#song_album_id").html(result["result"]);
        }});
      }
    });
});
</script>

app/views/songs/index.html.erb
<h1>Songs</h1>

 <div class="row">
   <div class="col-md-6">
      <%= link_to 'New song', new_song_path, class: "btn btn-primary" %>
      <a class="btn btn-xs btn-default" href="/songs?sort_by=title">Sort by title</a>
      <a class="btn btn-xs btn-default" href="/songs">Sort by time</a>
   </div>
   <div class="col-md-6">
     <div class="pull-right">
      <%= will_paginate @songs, renderer: BootstrapPagination::Rails %>
     </div>



   </div>
 </div>

 <br>
  <% @songs.each do |song| %>
    <div class="row well">
      <div class="col-md-8">
        <h3><%= song.title %></h3>
        <p><b>Album</b>: <%= song.album.name  %></p>
        <p><b>Artist</b>: <%= song.artist.name  %></p>

        <p><b>Lyrics</b>: <%= truncate song.lyrics.gsub(/\n/, '').html_safe, length:20 %></p>

        <p><%= link_to 'View complete lyrics', song_path(song), class: "btn btn-default" %>
        <% if song.user == current_user %>
          <%= link_to 'Edit', edit_song_path(song), class: "btn btn-default"  %></p>
        <% end %>

        <div>
          Rate the quality  : <%= rating_for song, "quality", :disable_after_rate => false %>
         </div>
      </div>
      <div class="col-md-4">
        <% if song.youtube_url? %>
          <%= youtube_embed(song.youtube_url).html_safe %>
        <% end %>

      </div>
    </div>
  <% end %>

app/views/songs/new.html.erb
<h1>Create an song:</h1>
<%= form_for :song, url: songs_path, html: {id: "new_song_create"} do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control custom_required", data: {
      validation: "required validate_min_length length5" } %>
    <%  if @song.errors[:title].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:title].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>
 
  <p>
    <%= f.label :lyrics %><br>
    <%= f.text_area :lyrics, class: "form-control lyrics custom_required"  %>
    <%  if @song.errors[:lyrics].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:lyrics].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>

  <p>
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url, class: "form-control"  %>
  </p>
  
  <p>
    <div><b>Select the artist:</b></div>
    <%= f.collection_select :artist_id, @artists , :id, :name, {prompt: "Select an artist"}, {class: "form-control custom_required"}  %>
    <%  if @song.errors[:artist_id].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:artist_id].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>
  
  <p>
    <div><b>Select the album:</b></div>
    <% if @albums != nil %>
      <%= f.collection_select :album_id, @albums , :id, :name, {prompt: "Select an album"}, {class: "form-control custom_required"}  %>
    <% else %>
      <select name="song[album_id]" id="song_album_id" class="form-control custom_required">
        <option value="">Select an album</option>
      <select>
    <% end %>
    <%  if @song.errors[:album_id].size != 0 %>
      <ul class="error_ul"><br><% @song.errors[:album_id].each do |error| %><li><%= error %></li><% end %></ul>
    <% end %>
  </p>
  <br><br>
  <p>
    <%= f.submit 'Create a new song', :class => 'btn btn-primary pull-right create_a_new_song_btn' %>
    <%= link_to 'Back', songs_path, :class => 'btn btn-default pull-right' %>
  </p>
<% end %>
<br><br><br><br><br><br><br><br>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#song_artist_id").on('change',function(){
      var artist_id = $(this).val();
      if (artist_id){
         $.ajax({url: "/get_albums_of_artist/" + artist_id, dataType: "json", success: function(result){
          $("#song_album_id").html(result["result"]);
        }});
      }
    });
    
    $(".create_a_new_song_btn").on("click", function(e){
      e.preventDefault();
      
      var false_count = 0;
      $(".custom_required").each(function() {
       
        if ($(this).val() == "" ){
          $(this).css("border","1px solid #a94442").css("border-radius","4px");
          false_count = false_count + 1;
        }
        else {
          $(this).css("border","1px solid #ccc").css("border-radius","4px");
        }
        
        if (false_count == 0){
          $("#new_song_create").submit();
        }
      });
      
      
    });
});
</script>

app/views/songs/show.html.erb
<h1>View song</h1>
    <div class="row well">
      <div class="col-md-8">
        <h3><%= @song.title %></h3>
        <% if @song.user == current_user %>
          <p><%= link_to 'Edit', edit_song_path(@song), class: "btn btn-default"  %></p>
        <% end %>
        <p><%= @song.lyrics.gsub(/\n/, '<br/>').html_safe %></p>
        <p><b>Album</b>: <%= Album.find(@song.album_id).name if @song.album_id?  %></p>
        <p><b>Artist</b>: <%= Artist.find(@song.artist_id).name if @song.artist_id? %></p>
      </div>
      <div class="col-md-4">
        <% if @song.youtube_url? %></p>
          <%= youtube_embed(@song.youtube_url).html_safe %>
        <% end %>
      </div>
    </div>

<hr>
    <h2 id="comments">Comments</h2>
    <% @song.comments.each do |comment| %>
        <p>
          <strong><%= comment.user.email %>:</strong>
          <%= comment.comment %>
        </p>
    <% end %>

  <hr>
  <h3>Add a comment:</h3>
  <%= form_for [@song, Comment.new] do |f| %>

    <p>
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>


<%= link_to 'Back', songs_path %>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#new_comment input[name=commit]").on('click',function(e){
      e.preventDefault();
      comment = $('textarea#comment_comment').val();
      if (comment.trim().length > 0) {
        $("#new_comment").submit();
        return true;
      }
      else{
        $("#comment_comment").css("border","1px solid #a94442").css("border-radius","4px");
      }
    });
});
</script>