config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  root 'welcome#index'
  
  resources :artists
  resources :albums do
    resources :comments, module: :albums
  end
  resources :songs do
    resources :comments, module: :songs
  end
  
  get 'get_albums_of_artist/:artist_id' => 'songs#get_albums_of_artist'
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist
  has_many :songs
  has_many :comments, as: :commentable

  mount_uploader :picture, PictureUploader

  validates :name, presence: true, length: { minimum: 5 }
  validates :description, presence: true, length: { minimum: 15 }
  validate :picture_size

  private

  def picture_size
    if picture.size > 5.megabytes
        errors.add(:picture, "Should be less than 5MB.")
    end
  end
end

app/controllers/albums/comments_controller.rb
class Albums::CommentsController < CommentsController
    before_action :set_commentable
    
    private
        def set_commentable
            @commentable = Album.find(params[:album_id])
        end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_album, only: [:show, :edit, :update]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album
    else
      render 'new'
    end

  end

  def show
  end

  def edit
  end

  def update

    if @album.update(album_params)
      redirect_to @album
    else
      render 'edit'
    end
  end

  private

  def find_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:name, :description, :picture, :artist_id)
  end



end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h1>Editing Album</h1>
 
<%= form_for :album, url: album_path(@album), method: :patch, html: { multipart: true } do |f| %>
  
  <%= render :partial => "layouts/error", :locals => {:object => @album} %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </p>

  <p>
    <div>Select the artist:</div>
    <%= f.collection_select :artist_id, Artist.all, :id, :name, prompt: true  %>
  </p>
  
  <p class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Albums</h1>
 <%= link_to 'New article', new_album_path, class: "btn btn-primary" %>
 <br><br>
<table class="table">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Artist</th>
     <th>View</th>
     <th>Edit</th>
  </tr>
 
  <% @albums.each do |album| %>
    <tr>
      <td><%= album.name %></td>
      <td><%= album.description %></td>
      <td><%= album.artist.name if album.artist_id? %></td>
      <td><%= link_to 'Show', album_path(album) %></td>
      <td><%= link_to 'Edit', edit_album_path(album) %></td>
    </tr>
  <% end %>
</table>

app/views/albums/new.html.erb
<h1>Create an album:</h1>
<%= form_for :album, url: albums_path, html: { multipart: true } do |f| %>

  <%= render :partial => "layouts/error", :locals => {:object => @album} %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </p>
  
  <p>
    <div>Select the artist:</div>
    <%= f.collection_select :artist_id, Artist.all, :id, :name, prompt: true  %>
  </p>
  
  <p class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<h1>View Album</h1>
<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist.name if @album.artist_id? %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<p>
  <%= image_tag(@album.picture.url, width: "250") if @album.picture? %>
</p>


<hr>
    <h2>Comments</h2>
    <% @album.comments.each do |comment| %>
      <p>
        <strong><%= comment.user.email %>:</strong>
        <%= comment.comment %>
      </p>
    <% end %>

  <hr>
  <h3>Add a comment:</h3>
  <%= form_for [@album, Comment.new] do |f| %>

    <p>
      <%= f.label :comment %><br>
      <%= f.text_area :comment %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>


<%= link_to 'Back', albums_path %>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#new_comment input[name=commit]").on('click',function(e){
      e.preventDefault();
      comment = $('textarea#comment_comment').val();
      if (comment.trim().length > 0) {
        $("#new_comment").submit();
        return true;
      }
      else{
        $("#comment_comment").css("border","1px solid #a94442").css("border-radius","4px");
      }
    });
});
</script>